Improved ANSIBLE_DIRECTORY validation to support the repository root
github/super-linter pull request #1111
Opened 2020-12-30 21:58 UTC by aaronsky

Fixes #1110, which prevents linting playbooks at the root of the repository from being supported.

## Proposed Changes

1. Support `ANSIBLE_DIRECTORY` values `"."`, `"/"`, and `"/${{ github.workspace }}"`
2. Update Ansible lint command to change into the `$ANSIBLE_DIRECTORY`, rather than the hardcoded `${GITHUB_WORKSPACE}/ansible` location. 
3. Changes should be purely additive and backwards compatible.

I tested these changes by building my fork locally in Docker and running several commands against my repo. [Logs are attached](https://github.com/github/super-linter/files/5755845/super-linter.log) for each run, plus some others not listed below:

```
docker run -e RUN_LOCAL=true -e ANSIBLE_DIRECTORY="//tmp/lint" -v $HOME/dotfiles:/tmp/lint 296d67fdca4c
docker run -e RUN_LOCAL=true -e ANSIBLE_DIRECTORY="/" -v $HOME/dotfiles:/tmp/lint 0534dd43cb81
docker run -e RUN_LOCAL=true -e ANSIBLE_DIRECTORY="/horace" -v $HOME/dotfiles:/tmp/lint 0534dd43cb81
docker run -e RUN_LOCAL=true -e ANSIBLE_DIRECTORY="" -v $HOME/dotfiles:/tmp/lint 0534dd43cb81
docker run -e RUN_LOCAL=true -e ANSIBLE_DIRECTORY="." -v $HOME/dotfiles:/tmp/lint 0534dd43cb81
```

## Readiness Checklist

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2020-12-30 22:00 UTC, Vowakula82 approved these changes

2020-12-30 22:01 UTC, Vowakula82 submitted a review, later dismissed

2020-12-30 22:04 UTC, Vowakula82 approved these changes

2020-12-30 22:15 UTC, Vowakula82 approved these changes

2020-12-30 22:46 UTC, ferrarimarco commented on lib/functions/worker.sh
> +          cd "${ANSIBLE_DIRECTORY}" || exit
Looks like a legit fix. Good catch!

2020-12-30 22:51 UTC, ferrarimarco requested changes

2020-12-30 22:51 UTC, ferrarimarco commented on lib/functions/validation.sh
> +    if [[ ${ANSIBLE_DIRECTORY} == "." ]] || [[ ${ANSIBLE_DIRECTORY} == "${GITHUB_WORKSPACE}" ]]; then
The second condition implies that `ANSIBLE_DIRECTORY` might not be relative to `GITHUB_WORKSPACE`, but it is!

2020-12-30 22:52 UTC, ferrarimarco commented
I think this should be a matter of setting `ANSIBLE_DIRECTORY=.` and handling just this corner case.

2020-12-30 22:55 UTC, aaronsky commented on lib/functions/validation.sh
> +    if [[ ${ANSIBLE_DIRECTORY} == "." ]] || [[ ${ANSIBLE_DIRECTORY} == "${GITHUB_WORKSPACE}" ]]; then
At this point, it's still unsanitized input, so it isn't treated as relative yet. So if someone really wanted to explicitly pass their `GITHUB_WORKSPACE`, I added a condition to express that correctly. I can remove this if you'd prefer not to support that, since it could constitute undefined behavior.

2020-12-30 23:00 UTC, Vowakula82 approved these changes

2020-12-30 23:01 UTC, aaronsky commented on lib/functions/validation.sh
> +    if [[ ${ANSIBLE_DIRECTORY} == "." ]] || [[ ${ANSIBLE_DIRECTORY} == "${GITHUB_WORKSPACE}" ]]; then
I think I see your point better now. I've pushed a new commit, let me know if that sorts this out and if my accompanying docs change makes sense. Thanks!

2020-12-30 23:04 UTC, ferrarimarco requested changes

2020-12-30 23:04 UTC, ferrarimarco commented on lib/functions/validation.sh
> +    if [[ ${ANSIBLE_DIRECTORY} == "." ]]; then
I'd rather not change the value of `ANSIBLE_DIRECTORY`. Can you just use a single `if` and set `TEMP_ANSIBLE_DIRECTORY` directly? Perhaps I'm missing something (late in my timezone LOL).

2020-12-30 23:06 UTC, aaronsky commented on lib/functions/validation.sh
> +    if [[ ${ANSIBLE_DIRECTORY} == "." ]]; then
Sure, let me update this real quick. 👍🏼 

Also if it's late for you, we can leave it until tomorrow or to someone else 🙂 This is only blocking my use of super-linter on a personal project.

2020-12-30 23:07 UTC, Vowakula82 approved these changes

2020-12-30 23:15 UTC, Vowakula82 approved these changes

2021-01-04 18:05 UTC, admiralAwkbar approved these changes
very nice!

2021-01-04 18:31 UTC, aaronsky commented
Thanks for the approval @admiralAwkbar! @ferrarimarco Is there anything else you want changed before this can be merged?

2021-01-04 19:38 UTC, merged