Incpes Tests
github/super-linter pull request #1497
Opened 2021-04-30 17:55 UTC by admiralAwkbar

- Adding Inspec tests to the test suite

2021-04-30 22:28 UTC, ferrarimarco commented
@admiralAwkbar I'd try with the [InSpec shell](https://docs.chef.io/inspec/cli/#shell), and run the same check there and see if it keeps failing

2021-04-30 22:33 UTC, ferrarimarco commented
Plus, there are more leftovers to remove :)

See the [TEST_CASE_RUN variable](https://github.com/github/super-linter/search?q=TEST_CASE_RUN), and where it's called (including [a workflow step](https://github.com/github/super-linter/blob/master/.github/workflows/deploy-DEV.yml#L134))

2021-05-03 14:14 UTC, admiralAwkbar commented
added #1509 to track the issue with those npm packages

2021-05-03 16:16 UTC, ferrarimarco requested changes

2021-05-03 16:16 UTC, ferrarimarco commented on Dockerfile
> +COPY --from=lintr-lib /usr/lib/R/library/ /usr/lib/r-library
I'd add a test for this (and similar directives). See https://docs.chef.io/inspec/resources/file/

2021-05-03 21:30 UTC, merged