Ignore files marked with @generated marker
github/super-linter pull request #1689
Opened 2021-06-23 00:24 UTC by stepancheg

`@generated` marker is used by certain tools to understand that the
file is generated, so it should be treated differently than a file
written by a human:
* these files do not need to be reformatted,
* diffs in these files are less important,
* and linters should not be invoked on these files.

This PR proposes builtin support for `@generated` marker.

I have not found a standard for a generated file marker, but:
* Facebook [uses `@generated` marker](https://tinyurl.com/fb-generated)
* Phabricator tool which was spawned from Facebook internal tool
  [also understands `@generated` marker](https://git.io/JnVHa)
* Cargo inserts `@generated` marker into [generated Cargo.lock files](https://git.io/JnVHP)

## Test Plan:

Create a test file `test.sh`:

```
echo $a
```

Run:

```
docker run -e RUN_LOCAL=true -v $HOME/tmp/g:/tmp/lint super-linter-test
```

Result is:

```
In /tmp/lint/test.sh line 1:
echo $a
^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
     ^-- SC2154: a is referenced but not assigned.
     ^-- SC2086: Double quote to prevent globbing and word splitting.
...
2021-06-22 23:46:16 [ERROR]   ERRORS FOUND in BASH:[1]
```

Now add `@generated` to the file and run again:

```
2021-06-22 23:47:13 [NOTICE]   All file(s) linted successfully with no errors detected
```

Additionally, add `@not-generated` in addition to `@generated`, and
linter error pops up again.

## Readiness Checklist

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2021-06-23 00:25 UTC, stepancheg commented
Perhaps this need to be labeled as "enhancement" but GitHub doesn't allow me to do that.

2021-06-23 08:36 UTC, ferrarimarco commented
@stepancheg thanks for this PR!

This looks interesting. I added a few comments

2021-06-23 08:40 UTC, ferrarimarco requested changes

2021-06-23 08:40 UTC, ferrarimarco commented on README.md
> +
Could be useful to:

1. Add an example.
2. Add a link in the README to the [FB blog post](https://engineering.fb.com/2015/08/20/open-source/writing-code-that-writes-code-with-hack-codegen/) you mentioned to get some context.

2021-06-23 08:40 UTC, ferrarimarco commented on lib/functions/buildFileList.sh
> +    if IsGenerated "$FILE"; then
I think we should make this check configurable with an environment variable that defaults to something that doesn't enable this check, so that we don't break existing functionality.

2021-06-23 20:04 UTC, stepancheg commented on lib/functions/buildFileList.sh
> +    if IsGenerated "$FILE"; then
I'll add an environment variable, but maybe use that environment variable to opt-out rather than opt-in?

super-linters breaks things all the time (when it adds more linters which are on by default), so another possible incompatibility is IMHO OK.

Another option is to start with out-in and eventually switch it to opt-out.

2021-06-23 20:57 UTC, stepancheg commented
Amended the PR:
* use `IGNORE_GENERATED_FILES` variable, `false` by default
* more documentation

2021-06-23 21:40 UTC, ferrarimarco requested changes

2021-06-23 21:40 UTC, ferrarimarco commented on README.md
> +| **IGNORE_GENERATED_FILES**         | `true`                          | If set to `true`, super-linter will ignore all the files with `@generated` marker but without `@not-generated` marker.
I think this should state `false` :)

2021-06-23 21:41 UTC, ferrarimarco commented
Nice work!

2021-06-23 21:47 UTC, stepancheg commented on README.md
> +| **IGNORE_GENERATED_FILES**         | `true`                          | If set to `true`, super-linter will ignore all the files with `@generated` marker but without `@not-generated` marker.
Always had trouble with double negations. Thanks!

2021-06-23 21:47 UTC, stepancheg commented
Updated the readme.

2021-06-24 00:24 UTC, stepancheg commented
I have created a little website to promote `@generated` marker: https://generated.at/

2021-06-24 08:07 UTC, ferrarimarco commented
@admiralAwkbar want to have a look as well?

2021-06-24 13:38 UTC, admiralAwkbar reviewed
This looks really good!
I need to get a fix in for the phar that's breaking all current builds... Shoudl have that done today and we can merge master into this branch and see where it goes!

Thanks for the cool work!

2021-06-24 16:59 UTC, admiralAwkbar approved these changes
looks good

2021-06-25 14:18 UTC, admiralAwkbar commented
@ferrarimarco all good to you?

2021-06-25 15:57 UTC, admiralAwkbar commented
So the fail was from `Raku` as when you run the version command it returns non ascii chars... its super dumb... So I had to update the command to pull those out and stop making the `makefile` angry...

2021-06-28 12:59 UTC, merged