Add source variables from env file
github/super-linter pull request #3270
Opened 2022-08-22 16:33 UTC by BryanQuigley

This allows to stop requiring duplication of most env variables if you
use something like STRTA - for example:
[test script](https://github.com/azavea/echo-locator/blob/273f543ca734c813c16cda8f3750fcf35f6356a3/scripts/test#L41)
and [ci build](https://github.com/azavea/echo-locator/blob/273f543ca734c813c16cda8f3750fcf35f6356a3/.github/workflows/ci.yml#L43)

Instead you can just put the shared env variables in .github/super-linter.env and super-linter will pull from their by
default (can also override).

Resolves: #2851

Note: Would like to get CI build to test it, to confirm doc changes are what I would expect.

Fixes #

## Proposed Changes

1. ...
2. ...
3. ...

## Readiness Checklist

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2022-09-03 14:49 UTC, lindluni submitted a review, later dismissed

2022-09-03 15:06 UTC, ferrarimarco requested changes

2022-09-03 15:06 UTC, ferrarimarco commented on lib/linter.sh
> +if test -f "$SUPER_LINTER_ENV_FILE"; then
Instead of `test` use `[` and `]` for consistency with other `if`s

2022-09-03 15:06 UTC, ferrarimarco commented on lib/linter.sh
> +  source SUPER_LINTER_ENV_FILE
This should be `source "$SUPER_LINTER_ENV_FILE"`

2022-09-03 15:06 UTC, ferrarimarco commented on lib/linter.sh
> +if test -f "$SUPER_LINTER_ENV_FILE"; then
What if the file exists and is not readable?

2022-09-03 15:06 UTC, ferrarimarco commented on lib/linter.sh
> +  source SUPER_LINTER_ENV_FILE
Add relevant logging, both info and debug (add more explanation in this case).

2022-09-03 15:08 UTC, ferrarimarco requested changes
Hi! Thanks for this PR. I've added a few comments to address.

2022-09-03 15:08 UTC, ferrarimarco commented on README.md
> +The super-linter allows you to pass the following `ENV` variables to be able to trigger different functionality. You can also specify environment variables in .github/super-linter.env which will be u
Can you add an example?

2022-09-03 15:08 UTC, ferrarimarco commented on lib/linter.sh
> +SUPER_LINTER_ENV_FILE="${SUPER_LINTER_ENV_FILE:-.github/super-linter.env}" # Default env file name
The `SUPER_LINTER_ENV_FILE` environment variable needs to be added to the README in the env vars table.

2022-09-03 15:14 UTC, ferrarimarco commented
@admiralAwkbar Besides the (small) issues I spotted, I remember we had this discussion already and we didn't go ahead with the approach of having environment variables defined in a file that `super-linter` had to source. I don't remember the specific reasons behind that decision, but I see a couple now:

- There are two ways of configuring super-linter (env vars, env file) which may conflict (which way is the preferred one, if a user configures both? shall we warn the user in that case? If so, this requires some refactoring).
- This is easily accomplishable without super-linter offering any built-in support. Users can source that environment file as part of the command (action, from the shell...) that they use to run super-linter. ([docker run example](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file)).

2022-09-06 22:34 UTC, BryanQuigley commented
@ferrarimarco that works too.  I thought I tried that but I guess I didn't have the syntax right.

I'd like to end this PR and make a new one that just documents how to do this. I've got it working here: https://github.com/azavea/echo-locator/pull/581

Feedback very welcome before I start a new PR.  Like, Is there a better way then `cat .github/super-linter.env >> $GITHUB_ENV`  to do this?

Thanks!
Bryan

2022-09-26 17:49 UTC, BryanQuigley commented
Closing this in favor of just a doc change: #3351

2022-09-26 17:49 UTC, closed without merging