Add `GITHUB_ACTIONS_COMMAND_ARGS` environment variable to define additional arguments for `actionlint` command
github/super-linter pull request #3451
Opened 2022-10-16 11:39 UTC by rhysd

Fixes #1852

## Proposed Changes

1. Define `GITHUB_ACTIONS_COMMAND_ARGS` environment variable
2. Pass the environment variable as argument of `actionlint`

## Readiness Checklist

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

---

This is a revised PR of #1853.

The context of this change is that `actionlint` provides some configuration via only command line arguments (for example, ignore some errors). But there is no way to add arguments in Super-Linter. This PR adds a way to define additional arguments via the environment variable.

#1853 was closed in favor of #1667. But #1667 was closed as stale. So the issue #1852 was left unresolved.

2022-10-16 12:21 UTC, rhysd commented
Ci seemed to fail at `TYPESCRIPT_STANDARD` linter, unrelated to this PR.

```
2022-10-16 12:05:59 [ERROR]   ERRORS FOUND in TYPESCRIPT_STANDARD:[1]
```

2022-10-17 09:57 UTC, ferrarimarco requested changes

2022-10-17 09:57 UTC, ferrarimarco commented on lib/linter.sh
> +if [ "${GITHUB_ACTIONS_COMMAND_ARGS}" = "null" ] || [ -z "${GITHUB_ACTIONS_COMMAND_ARGS}" ]; then
Set the default value as we're doing with the `KUBERNETES_KUBEVAL_OPTIONS` variable

2022-10-17 10:00 UTC, ferrarimarco commented
Seems so:

```
2022-10-16 12:05:56 [DEBUG]   Running LintCodebase. FILE_TYPE: TYPESCRIPT_STANDARD. Linter name: ts-standard, linter command: ts-standard --parser @typescript-eslint/parser --plugin @typescript-eslint/eslint-plugin --project /tmp/lint/.github/linters/tsconfig.json --env browser --env es6 --env jest, TEST_CASE_RUN: true, FILTER_REGEX_INCLUDE: , FILTER_REGEX_EXCLUDE:  files to lint: /tmp/lint/.automation/test/jscpd/typescript_good_1 copy.ts /tmp/lint/.automation/test/jscpd/typescript_good_1.ts /tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts /tmp/lint/.automation/test/typescript_es/typescript_good_1.ts /tmp/lint/.automation/test/typescript_standard/typescript_bad_1.ts /tmp/lint/.automation/test/typescript_standard/typescript_good_1.ts
2022-10-16 12:05:56 [INFO]   Testing Codebase [TYPESCRIPT_STANDARD] files...
2022-10-16 12:05:56 [INFO]   ----------------------------------------------
2022-10-16 12:05:56 [INFO]   ----------------------------------------------
2022-10-16 12:05:56 [DEBUG]   Linting FILE: /tmp/lint/.automation/test/jscpd/typescript_good_1 copy.ts
2022-10-16 12:05:56 [DEBUG]   File: /tmp/lint/.automation/test/jscpd/typescript_good_1 copy.ts, FILE_NAME: typescript_good_1 copy.ts, DIR_NAME:/tmp/lint/.automation/test/jscpd, FILE_STATUS: good, INDIVIDUAL_TEST_FOLDER: typescript_standard, TEST_CASE_DIRECTORY: .automation/test/typescript_standard
2022-10-16 12:05:56 [DEBUG]   TYPESCRIPT_STANDARD expects to lint individual files. Updated TEST_CASE_DIRECTORY to: .automation/test/typescript_standard/
2022-10-16 12:05:56 [DEBUG]   Skipping /tmp/lint/.automation/test/jscpd/typescript_good_1 copy.ts because it's not in the test case directory for TYPESCRIPT_STANDARD...
2022-10-16 12:05:56 [DEBUG]   Linting FILE: /tmp/lint/.automation/test/jscpd/typescript_good_1.ts
2022-10-16 12:05:56 [DEBUG]   File: /tmp/lint/.automation/test/jscpd/typescript_good_1.ts, FILE_NAME: typescript_good_1.ts, DIR_NAME:/tmp/lint/.automation/test/jscpd, FILE_STATUS: good, INDIVIDUAL_TEST_FOLDER: typescript_standard, TEST_CASE_DIRECTORY: .automation/test/typescript_standard
2022-10-16 12:05:56 [DEBUG]   TYPESCRIPT_STANDARD expects to lint individual files. Updated TEST_CASE_DIRECTORY to: .automation/test/typescript_standard/
2022-10-16 12:05:56 [DEBUG]   Skipping /tmp/lint/.automation/test/jscpd/typescript_good_1.ts because it's not in the test case directory for TYPESCRIPT_STANDARD...
2022-10-16 12:05:56 [DEBUG]   Linting FILE: /tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts
2022-10-16 12:05:56 [DEBUG]   File: /tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts, FILE_NAME: typescript_bad_1.ts, DIR_NAME:/tmp/lint/.automation/test/typescript_es, FILE_STATUS: bad, INDIVIDUAL_TEST_FOLDER: typescript_standard, TEST_CASE_DIRECTORY: .automation/test/typescript_standard
2022-10-16 12:05:56 [DEBUG]   TYPESCRIPT_STANDARD expects to lint individual files. Updated TEST_CASE_DIRECTORY to: .automation/test/typescript_standard/
2022-10-16 12:05:56 [DEBUG]   Skipping /tmp/lint/.automation/test/typescript_es/typescript_bad_1.ts because it's not in the test case directory for TYPESCRIPT_STANDARD...
2022-10-16 12:05:56 [DEBUG]   Linting FILE: /tmp/lint/.automation/test/typescript_es/typescript_good_1.ts
2022-10-16 12:05:56 [DEBUG]   File: /tmp/lint/.automation/test/typescript_es/typescript_good_1.ts, FILE_NAME: typescript_good_1.ts, DIR_NAME:/tmp/lint/.automation/test/typescript_es, FILE_STATUS: good, INDIVIDUAL_TEST_FOLDER: typescript_standard, TEST_CASE_DIRECTORY: .automation/test/typescript_standard
2022-10-16 12:05:56 [DEBUG]   TYPESCRIPT_STANDARD expects to lint individual files. Updated TEST_CASE_DIRECTORY to: .automation/test/typescript_standard/
2022-10-16 12:05:56 [DEBUG]   Skipping /tmp/lint/.automation/test/typescript_es/typescript_good_1.ts because it's not in the test case directory for TYPESCRIPT_STANDARD...
2022-10-16 12:05:56 [DEBUG]   Linting FILE: /tmp/lint/.automation/test/typescript_standard/typescript_bad_1.ts
2022-10-16 12:05:56 [DEBUG]   File: /tmp/lint/.automation/test/typescript_standard/typescript_bad_1.ts, FILE_NAME: typescript_bad_1.ts, DIR_NAME:/tmp/lint/.automation/test/typescript_standard, FILE_STATUS: bad, INDIVIDUAL_TEST_FOLDER: typescript_standard, TEST_CASE_DIRECTORY: .automation/test/typescript_standard
2022-10-16 12:05:56 [DEBUG]   TYPESCRIPT_STANDARD expects to lint individual files. Updated TEST_CASE_DIRECTORY to: .automation/test/typescript_standard/
2022-10-16 12:05:56 [INFO]   ---------------------------
2022-10-16 12:05:56 [INFO]   File:[/tmp/lint/.automation/test/typescript_standard/typescript_bad_1.ts]
2022-10-16 12:05:56 [INFO]    - File:[typescript_bad_1.ts] failed test case (Error code: 1) with [ts-standard] successfully
2022-10-16 12:05:57 [DEBUG]   Error code: 1. Command output:
------
Unable to locate the project file. A project file (tsconfig.json or tsconfig.eslint.json) is required in order to use ts-standard.
------
2022-10-16 12:05:57 [DEBUG]   Linting FILE: /tmp/lint/.automation/test/typescript_standard/typescript_good_1.ts
2022-10-16 12:05:57 [DEBUG]   File: /tmp/lint/.automation/test/typescript_standard/typescript_good_1.ts, FILE_NAME: typescript_good_1.ts, DIR_NAME:/tmp/lint/.automation/test/typescript_standard, FILE_STATUS: good, INDIVIDUAL_TEST_FOLDER: typescript_standard, TEST_CASE_DIRECTORY: .automation/test/typescript_standard
2022-10-16 12:05:57 [DEBUG]   TYPESCRIPT_STANDARD expects to lint individual files. Updated TEST_CASE_DIRECTORY to: .automation/test/typescript_standard/
2022-10-16 12:05:57 [INFO]   ---------------------------
2022-10-16 12:05:57 [INFO]   File:[/tmp/lint/.automation/test/typescript_standard/typescript_good_1.ts]
2022-10-16 12:05:57 [DEBUG]   Found errors. Error code: 1, File type: TYPESCRIPT_STANDARD, Error on missing exec bit: true
2022-10-16 12:05:57 [ERROR]   Found errors in [ts-standard] linter!
2022-10-16 12:05:57 [ERROR]   Error code: 1. Command output:
------
Unable to locate the project file. A project file (tsconfig.json or tsconfig.eslint.json) is required in order to use ts-standard.
------
2022-10-16 12:05:57 [DEBUG]   Error code: 1. Command output:
------
Unable to locate the project file. A project file (tsconfig.json or tsconfig.eslint.json) is required in order to use ts-standard.
------
```

2022-10-17 12:29 UTC, rhysd commented on lib/linter.sh
> +if [ "${GITHUB_ACTIONS_COMMAND_ARGS}" = "null" ] || [ -z "${GITHUB_ACTIONS_COMMAND_ARGS}" ]; then
Thank you for the point. I initialized the variable with the default value `null` at 05f6de33deaae3cb31cc328686aa806f5860f030.

2022-10-18 11:31 UTC, ferrarimarco approved these changes

2022-12-20 17:52 UTC, lindluni commented
@rhysd 

Thank you for the enhancement. We just fixed our dependency chain after a few months of it being broken due to an upstream dependency. Can you rebase your branch on the latest changes to pick up the vulnerability fix that is flagged here.

2023-01-04 05:35 UTC, lindluni commented
Added here: https://github.com/github/super-linter/pull/3772

2023-01-04 05:35 UTC, closed without merging