R fix dependency installation
github/super-linter pull request #3501
Opened 2022-10-28 17:43 UTC by tonyk7440

Fixes #3473 

## Proposed Changes

1. ...
2. ...
3. ...

## Readiness Checklist

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2022-11-28 12:01 UTC, tonyk7440 commented
Not stale, waiting on review of PR

2023-01-04 17:31 UTC, ferrarimarco commented on lib/functions/detectFiles.sh
> +        R -e "install.packages('remotes', repos = 'https://cloud.r-project.org/')"
Can you redirect stderr to stdout here as well? So we get the complete output when debugging

2023-01-09 15:35 UTC, tonyk7440 commented on lib/functions/detectFiles.sh
> +        R -e "install.packages('remotes', repos = 'https://cloud.r-project.org/')"
@ferrarimarco Done now I think

2023-01-10 09:22 UTC, ferrarimarco requested changes

2023-01-10 09:22 UTC, ferrarimarco commented on lib/functions/detectFiles.sh
Thanks for the update.

I think the build is complaining.

From the [log](https://github.com/github/super-linter/actions/runs/3875288592/jobs/6608799248#step:9:2686):

```
2023-01-09 16:47:44 [INFO]   Trying to install the R package inside:[/tmp/lint/.automation/test]
2023-01-09 16:47:45 [WARN]   ERROR! Failed to run:[R CMD build] at location:[/tmp/lint/.automation/test]
2023-01-09 16:47:45 [WARN]   BUILD_CMD:[* checking for file ‘/tmp/lint/.automation/test/DESCRIPTION’ ... NO]
```

We should make the build fail in that case so we get noticed of this issue during tests.

(Apparently, I can't request changes on lines you didn't modify from the GitHub GUI, so I'll write the details here directly.)

Can you please change the following check, starting on line 494 from:

```shell
      if [ "${ERROR_CODE}" -ne 0 ]; then
        # Error
        warn "ERROR: Failed to install the build package at:[${BUILD_PKG}]"
        warn "INSTALL_CMD:[${INSTALL_CMD}]"
      fi
```

to:

```shell
      debug "INSTALL_CMD:[${INSTALL_CMD}]"
      if [ "${ERROR_CODE}" -ne 0 ]; then
        fatal "ERROR: Failed to install the build package at:[${BUILD_PKG}]"
      fi
```

After that, we can troubleshoot the failure.

Thanks!

2023-01-16 18:30 UTC, tonyk7440 commented on lib/functions/detectFiles.sh
Hi @ferrarimarco , thanks, just updated the code according to your comment

2023-02-14 19:08 UTC, tonyk7440 commented
Hi @ferrarimarco , could you perhaps review again?

Thanks!

2023-04-10 20:27 UTC, ferrarimarco approved these changes

2023-04-10 23:29 UTC, merged