replace kubeval with kubeconform
github/super-linter pull request #3607
Opened 2022-12-08 04:25 UTC by chenrui333

Fixes #

## Proposed Changes

1. ...
2. ...
3. ...

## Readiness Checklist

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

----

replacing kubeval with kubeconform as kubeval is no longer maintained.

- relates to https://github.com/instrumenta/kubeval/issues/268

2022-12-21 07:35 UTC, ferrarimarco requested changes

2022-12-21 07:35 UTC, ferrarimarco commented on Dockerfile
> +ARG KUBECONFORM_VERSION='v0.5.0'
Given that Kubeconform has a container image available, can you please refactor this PR to use that? By doing that, we can leverage Dependabot for updates. Thanks!

2022-12-22 17:44 UTC, chenrui333 commented on Dockerfile
> +ARG KUBECONFORM_VERSION='v0.5.0'
is there any documentation specifying which is preferred? I personally would vote for binary though.

2022-12-22 17:46 UTC, ferrarimarco commented on Dockerfile
> +ARG KUBECONFORM_VERSION='v0.5.0'
Basically, if a container image is available, we try using that so that Dependabot takes care of updating that. As you can see, in the current implementation, the Kubeconform image would need to be manually updated.

2023-01-22 23:33 UTC, lindluni commented
Added in #3800

2023-01-22 23:33 UTC, closed without merging