Simplify automation workflows
github/super-linter pull request #3689
Opened 2022-12-23 20:58 UTC by lindluni

Signed-off-by: Brett Logan <lindluni@github.com>

2023-01-04 17:21 UTC, ferrarimarco requested changes
A few small nits 😄

2023-01-04 17:21 UTC, ferrarimarco commented on .github/linters/actionlint.yaml
> +    - ubuntu-20.04-8core-sl
Maybe switch to Ubuntu 22.04 if available?

If you go this route, check the rest of the jobs as well for other 20.04 instances.

2023-01-04 17:21 UTC, ferrarimarco commented on .github/workflows/cd.yml
> +      - name: Start  ${{ matrix.images.environment }} Deployment
Remove extra space after `Start`

2023-01-04 17:21 UTC, ferrarimarco commented on .github/workflows/ci.yml
> +          load: false
I don't know if this is intended, but by setting this to false you are forcing the steps below (`Run Super-Linter tests` and `Lint Entire Codebase`) to pull the image from the registry. If you want to reuse the image you just built instead, you need to split this in two steps (one that loads, one that pushes) because the two settings cannot be set to `true` at the same time, IIRC.

In the current implementation, we also test if we're able to pull the standard image from the registry at least. We don't pull the slim one though.

2023-01-04 17:21 UTC, ferrarimarco commented on .github/workflows/release.yml
> +      - name: Update Major Version and Latest Git Tag
Is there a way to automatically bump the version in `action.yml` as well? I see that there are actions that do this, but I didn't try any.

2023-01-04 17:21 UTC, ferrarimarco commented on .github/workflows/stack-linter.yml
>  #############################
Isn't this workflow redundant at this point?

2023-01-04 17:33 UTC, lindluni commented on .github/workflows/stack-linter.yml
>  #############################
Probably, my initial run through was just splitting up what we had, I'll drop this since it runs as part of the other workflow.

2023-01-04 17:35 UTC, lindluni commented on .github/workflows/release.yml
> +      - name: Update Major Version and Latest Git Tag
Thats my top priority next. Having released last night and gone through that nightmare, we have to sort out a truly automated release process. I have some great plans, but I'm also waiting on GitHub to release some new features. We have some MAJOR changes coming to Actions maintenance and security this quarter that will probably render some of our workflows pointless afterwards.

2023-01-05 03:17 UTC, lindluni commented on .github/linters/actionlint.yaml
> +    - ubuntu-20.04-8core-sl
Right now we only have 20.04 available, this was custom built for Super-Linter, I have asked to get the new larger runners for us, but they asked if we could wait for the new runners to be widely available. So once they go GA we will swap to the ubuntu-22.04-8core-sl runners.

2023-01-05 03:48 UTC, lindluni commented on .github/workflows/ci.yml
> +          load: false
Good catch, bad copy-paste on my part. Fixed.

Do you think we need to test the pull? Can certainly add that, but I would expect the push to fail in the first place if there was going to be an issue with the registry, or is there another scenario you had in mind that caused it to be introduced before.

2023-01-05 09:31 UTC, ferrarimarco commented on .github/workflows/release.yml
> +      - name: Update Major Version and Latest Git Tag
Nice!

2023-01-05 09:32 UTC, ferrarimarco commented on .github/workflows/ci.yml
> +          load: false
SGTM!

2023-01-05 09:33 UTC, ferrarimarco approved these changes

2023-01-05 09:33 UTC, ferrarimarco commented
We might want to disable the `Stack linter` required check on the `main` branch protection rule.

2023-01-05 09:34 UTC, ferrarimarco commented
(I don't have the right privileges to do that)

2023-01-05 14:46 UTC, merged