Remove deprecated kubeval and replace with kubeconform
github/super-linter pull request #3800
Opened 2023-01-09 04:56 UTC by lindluni

Uses a Docker image instead of downloading binary as an enhancement to https://github.com/github/super-linter/pull/3607

2023-01-09 05:32 UTC, lindluni commented
Missed updating inspec test for proper version flag, will update in the morning.

2023-01-09 09:55 UTC, ferrarimarco requested changes

2023-01-09 09:55 UTC, ferrarimarco commented on lib/linter.sh
> +KUBERNETES_kubeconform_OPTIONS="${KUBERNETES_KUBECONFORM_OPTIONS:-null}"
This variable should be all uppercase

2023-01-09 09:55 UTC, ferrarimarco commented on README.md
We should also update the `VALIDATE_KUBERNETES_KUBEVAL ` and `KUBERNETES_KUBEVAL_OPTIONS` variables for Kubeconform in the README.

2023-01-09 09:55 UTC, ferrarimarco commented on .automation/test/kubernetes_kubeval/README.md
> +# Kubeconform Test Cases
Reminder to update the test directory name from `kubernetes_kubeval` to `kubernetes_kubeconform`

2023-01-11 15:54 UTC, lindluni commented on lib/linter.sh
> +KUBERNETES_kubeconform_OPTIONS="${KUBERNETES_KUBECONFORM_OPTIONS:-null}"
Thank you! Bad find-replace 😂

2023-01-11 16:22 UTC, lindluni commented on Dockerfile
> +RUN --mount=type=secret,id=GITHUB_TOKEN /install-ktlint.sh && rm -rf /install-ktlint.sh
This script needs to be broken out into separate scripts on what it actually does in a follow on PR as it's unrelated to this PR

2023-01-11 16:22 UTC, lindluni commented on lib/functions/linterVersions.sh
> +        GET_VERSION_CMD="$(${LINTER} -v)"
This is just alphabetically arranging the checks

2023-01-11 16:26 UTC, lindluni commented
I'd like to cut a release after #3812 is merged before merging this one, as it's a breaking change and will require a major version update

2023-01-11 16:26 UTC, ferrarimarco approved these changes

2023-01-12 20:41 UTC, ferrarimarco approved these changes

2023-01-17 02:14 UTC, merged

2023-02-08 15:51 UTC, KingBain commented
For what its worth, the github marketplace is mentioning that super linter is now using kubeconform, having just run github/super-linter@v4.10.1 

It is still running kubeval

not sure when the next release of superlinter will be but their is a mismatch there.