Add snakefmt support to super-linter
github/super-linter pull request #689
Opened 2020-09-07 15:00 UTC by kpj

[Snakemake](https://github.com/snakemake/snakemake/) is a Python-based workflow management system. It is organized in `Snakefiles` which can be linted using [snakefmt](https://github.com/snakemake/snakefmt).

This PR implements linting support for `Snakefiles`.

2020-09-08 07:45 UTC, kpj commented on lib/linter.sh
> +  LintCodebase "SNAKEMAKE_LINT" "snakemake --lint" "snakemake --lint -s" ".*\.\(smk\)\$" "\(Snakefile|.*\.smk\)\$" "${FILE_ARRAY_SNAKEMAKE[@]}"
Is it safe to assume that `LINTER_COMMAND` will always be followed by the source file?
The `-s` parameter requires this.

2020-09-08 09:03 UTC, lydz1209 requested changes

2020-09-08 09:03 UTC, lydz1209 commented on lib/linter.sh
> +  LintCodebase "SNAKEMAKE_LINT" "snakemake" "snakemake --lint -s" ".*\.\(smk\)\$" "\(Snakefile|.*\.smk\)\$" "${FILE_ARRAY_SNAKEMAKE[@]}"
fi

2020-09-08 09:27 UTC, kpj commented on lib/linter.sh
> +  LintCodebase "SNAKEMAKE_LINT" "snakemake" "snakemake --lint -s" ".*\.\(smk\)\$" "\(Snakefile|.*\.smk\)\$" "${FILE_ARRAY_SNAKEMAKE[@]}"
Thanks! Fixed it in the next commit.

2020-09-08 14:26 UTC, admiralAwkbar commented on lib/linter.sh
> +  LintCodebase "SNAKEMAKE_LINT" "snakemake --lint" "snakemake --lint -s" ".*\.\(smk\)\$" "\(Snakefile|.*\.smk\)\$" "${FILE_ARRAY_SNAKEMAKE[@]}"
@kpj YOu are correct to assume that command will be followed by the file being evaluated

2020-09-08 14:31 UTC, admiralAwkbar commented on lib/linter.sh
> +SNAKEMAKE_FILE_NAME="${SNAKEMAKE_CONFIG_FILE:-.snakefmt.toml}"
Can you add the variable to the dockerfile, and to the readme for documentation?

2020-09-08 14:31 UTC, admiralAwkbar commented
@kpj This is great work!
just a few things and I think were good to get this merged up

2020-09-08 15:24 UTC, admiralAwkbar commented
@kpj I took the liberty to get it done :)

2020-09-08 15:27 UTC, IAmHughes approved these changes

2020-09-08 15:31 UTC, merged

2020-09-09 08:04 UTC, kpj commented on lib/linter.sh
> +  LintCodebase "SNAKEMAKE_LINT" "snakemake --lint" "snakemake --lint -s" ".*\.\(smk\)\$" "\(Snakefile|.*\.smk\)\$" "${FILE_ARRAY_SNAKEMAKE[@]}"
Great, thanks!

2020-09-09 08:48 UTC, kpj commented
Awesome, thank you very much!

I have a question regarding testing this PR: In the workflow's `linter.yml` I tried both `uses: github/super-linter@master` and `uses: github/super-linter@133eb655ffcd8153daa551e87040883bcbb3e868` (instead of `uses: github/super-linter@v3`) in order to include Snakemake linting.
However, `github/super-linter:v3` keeps being used:
![image](https://user-images.githubusercontent.com/645279/92576262-9ad03880-f289-11ea-815b-e7d45768daf4.png)
Am I doing something obvious wrong?

(Sorry for polluting this PR, if this is not specific to this project I'll go and debug elsewhere 😃 )

2020-11-24 12:32 UTC, lydz1209 commented
Le mar. 8 sept. 2020, à 05 h 03, lydz1209 <notifications@github.com> a
écrit :

> *@lydz1209* requested changes on this pull request.
> ------------------------------
>
> In lib/linter.sh
> <https://github.com/github/super-linter/pull/689#discussion_r484764677>:
>
> > @@ -1859,7 +1859,7 @@ if [ "${VALIDATE_SNAKEMAKE_LINT}" == "true" ]; then
>    # Lint the files with snakefmt #
>    ################################
>    # LintCodebase "FILE_TYPE" "LINTER_NAME" "LINTER_CMD" "FILE_TYPES_REGEX" "FILE_ARRAY"
> -  LintCodebase "SNAKEMAKE_LINT" "snakemake --lint" "snakemake --lint -s" ".*\.\(smk\)\$" "\(Snakefile|.*\.smk\)\$" "${FILE_ARRAY_SNAKEMAKE[@]}"
> +  LintCodebase "SNAKEMAKE_LINT" "snakemake" "snakemake --lint -s" ".*\.\(smk\)\$" "\(Snakefile|.*\.smk\)\$" "${FILE_ARRAY_SNAKEMAKE[@]}"
>
> fi
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/super-linter/pull/689#pullrequestreview-483936843>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AODRKTM63ZIZ2TFSVSUB7XDSEXXOTANCNFSM4Q6MB5KQ>
> .
>