editorconfig-checker - Use .ecrc Files
github/super-linter pull request #824
Opened 2020-10-08 20:32 UTC by mshimokura

## Proposed Changes

1. Use the -config option for editorconfig-checker to specify an .ecrc file. This allows you to change the linter options, i.e. allowing spaces after tabs.
2. Add a variable EDITORCONFIG_FILE_NAME to specify the .ecrc file to use.

## Readiness Checklist

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2020-10-08 23:05 UTC, ferrarimarco commented
Hi! Nice work.

What if you change the variable name from `EDITORCONFIG_FILE_NAME` to `EDITORCONFIG_CHECKER_FILE_NAME`?

`EDITORCONFIG_FILE_NAME` might lead to confusion with the `.editorconfig` file itself.

Thoughts?

2020-10-09 13:18 UTC, mshimokura commented
actually, so I tried that out, and it doesn't work because there's a naming convention for the variables that it should be `${LANGUAGE_NAME}_FILE_NAME`. 
https://github.com/github/super-linter/blob/a5cada70f874be6fd70f8f780672d3cc2c645ba8/lib/linter.sh#L313

So, changing the variable name ends up making it not pick up the config file.

2020-10-09 14:24 UTC, joejump commented on lib/linter.sh
> -EDITORCONFIG_FILE_NAME='.ecrc'                                                  # Name of the file
>

2020-10-09 14:26 UTC, joejump requested changes
groovylintrc.json'

2020-10-12 15:23 UTC, admiralAwkbar approved these changes

2020-10-12 15:24 UTC, merged