add tfsec support
github/super-linter pull request #886
Opened 2020-10-20 01:59 UTC by zuphzuph

## Proposed Changes

1. add tfsec support

## Readiness Checklist

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2020-10-20 08:08 UTC, ferrarimarco requested changes

2020-10-20 08:08 UTC, ferrarimarco commented on docs/disabling-linters.md
> +- There is currently **No** Terragrunt format config rules file
tfsec, not terragrunt :)

2020-10-20 08:09 UTC, ferrarimarco commented
@zuphzuph thanks for this PR! Can you add the relevant test cases as well? Thanks!

2020-10-20 08:10 UTC, ferrarimarco commented on lib/linter.sh
> +  'TEKTON' 'TERRAFORM' 'TERRAFORM_TERRASCAN' 'TERRAGRUNT' 'TFSEC' 'TSX' 'TYPESCRIPT_ES' 'TYPESCRIPT_STANDARD' 'XML' 'YAML')
Can you change `TFSEC` to `TERRAFORM_TFSEC`? Remember to change all the related references! Thanks.

2020-10-20 13:57 UTC, ferrarimarco commented
@zuphzuph see https://github.com/github/super-linter/wiki/Adding-new-language-support for guidance about the tests. Let us know if you've questions :)

2020-10-20 16:18 UTC, zuphzuph commented
> @zuphzuph see https://github.com/github/super-linter/wiki/Adding-new-language-support for guidance about the tests. Let us know if you've questions :)

should be good to go now

2020-10-20 16:35 UTC, ferrarimarco requested changes
Just a few minor nits! Then we just have to wait for the checks to complete, and we should be good to go!

2020-10-20 16:35 UTC, ferrarimarco commented on .automation/test/terraform_tfsec/bad/terraform_bad_1.tf
> +}
Can you add a newline here?

2020-10-20 16:35 UTC, ferrarimarco commented on .automation/test/terraform_tfsec/good/terraform_good_1.tf
> +}
Can you add a newline here?

2020-10-20 16:35 UTC, ferrarimarco commented on Dockerfile
> +RUN tfsec
Why are you running tfsec when building the image?

2020-10-20 16:35 UTC, ferrarimarco commented on README.md
> +| **VALIDATE_TERRAFORM_TFSEC**      | `true`                | Flag to enable or disable the linting process of the Terraform language for security related issues.|
Can you update the descriptions here to state which linter you're using? Otherwise both say `security related issues`.

2020-10-20 16:35 UTC, ferrarimarco commented on docs/disabling-linters.md
> +- There is currently **No** way to disable rules inline of the file(s)
This is NOT true. See https://github.com/tfsec/tfsec#ignoring-warnings

2020-10-20 16:35 UTC, ferrarimarco commented on docs/disabling-linters.md
> +- There is currently **No** way to disable rules inline of the file(s)
This is NOT true. See https://github.com/tfsec/tfsec#ignoring-warnings

2020-10-21 10:56 UTC, ferrarimarco commented
The builds are failing because `tfsec` wants a directory, not single files. We need to add a special case, much like we're doing in the `LintAnsibleFiles` function.

PS: I was thinking of a way of getting rid of that special case altogether. If I were you, I'd implement a special case so that we can unblock this PR, without waiting for others.

2020-10-21 11:13 UTC, ferrarimarco requested changes

2020-10-21 11:13 UTC, ferrarimarco commented on lib/linter.sh
> +LINTER_COMMANDS_ARRAY['TERRAFORM_TFSEC']="tfsec"
Unfortunately, this is not enough because tfsec only supports linting whole directories. See my comment for more background

2020-11-01 20:28 UTC, closed without merging