fix: correct env variable name for JSX command
github/super-linter pull request #890
Opened 2020-10-21 19:10 UTC by ahmadnassri

Fixes #889

2020-10-21 19:18 UTC, ferrarimarco commented
Good catch!

2020-10-21 19:20 UTC, ferrarimarco requested changes

2020-10-21 19:33 UTC, ahmadnassri commented on lib/linter.sh
> +LINTER_COMMANDS_ARRAY['JSX']="eslint --no-eslintrc -c ${JSX_FILE_NAME}"
I don't see `JSX_LINTER_RULES` defined anywhere? (could it be auto generated? I didn't read the whole source code ... because it's too big! 😅 )

2020-10-21 20:25 UTC, ferrarimarco commented on lib/linter.sh
> +LINTER_COMMANDS_ARRAY['JSX']="eslint --no-eslintrc -c ${JSX_FILE_NAME}"
Correct! It's here: https://github.com/github/super-linter/blob/master/lib/linter.sh#L360

2020-10-21 20:59 UTC, ahmadnassri commented on lib/linter.sh
> +LINTER_COMMANDS_ARRAY['JSX']="eslint --no-eslintrc -c ${JSX_FILE_NAME}"
done

2020-10-21 21:21 UTC, GaboFDC approved these changes

2020-10-22 16:17 UTC, admiralAwkbar approved these changes

2020-10-23 07:16 UTC, ferrarimarco approved these changes

2020-10-23 07:17 UTC, merged